"""Rule manager for persisting and managing learned rules."""

import logging
from datetime import datetime, timedelta
from pathlib import Path

import yaml

from veridical.learning.models import LearnedRule

logger = logging.getLogger(__name__)

_LEARNED_RULES_SECTION_HEADER = "# Learned Rules"


class RuleManager:
    """Manages learned rules persisted in a YAML file."""

    def __init__(self, rules_file: Path) -> None:
        """Initialize the rule manager.

        Args:
            rules_file: Path to the learned rules YAML file.
        """
        self.rules_file = rules_file

    def load(self) -> list[LearnedRule]:
        """Load rules from the YAML file.

        Returns:
            List of LearnedRule objects.
        """
        if not self.rules_file.exists():
            return []

        try:
            with self.rules_file.open() as f:
                data = yaml.safe_load(f)
        except (yaml.YAMLError, OSError) as e:
            logger.warning(f"Failed to load rules from {self.rules_file}: {e}")
            return []

        if not data or not isinstance(data, dict):
            return []

        raw_rules = data.get("rules", [])
        if not isinstance(raw_rules, list):
            return []

        rules: list[LearnedRule] = []
        for item in raw_rules:
            try:
                rules.append(LearnedRule(**item))
            except Exception as e:
                logger.warning(f"Skipping invalid rule entry: {e}")

        return rules

    def save(self, rules: list[LearnedRule]) -> None:
        """Save rules to the YAML file.

        Args:
            rules: List of LearnedRule objects to persist.
        """
        self.rules_file.parent.mkdir(parents=True, exist_ok=True)

        data = {
            "rules": [
                {
                    "id": r.id,
                    "trigger_pattern": r.trigger_pattern,
                    "rule_text": r.rule_text,
                    "confidence_score": r.confidence_score,
                    "created_at": r.created_at.isoformat(),
                    "applied_count": r.applied_count,
                    "success_rate": r.success_rate,
                }
                for r in rules
            ]
        }

        with self.rules_file.open("w") as f:
            yaml.dump(data, f, default_flow_style=False, sort_keys=False)

        logger.info(f"Saved {len(rules)} rules to {self.rules_file}")

    def apply_to_agents_md(
        self,
        rules: list[LearnedRule],
        agents_md_path: Path,
        *,
        confirmed: bool = False,
    ) -> str:
        """Apply learned rules to AGENTS.md.

        Args:
            rules: Rules to apply.
            agents_md_path: Path to the AGENTS.md file.
            confirmed: Whether the user has confirmed the write.

        Returns:
            The diff preview string showing what would be appended.

        Raises:
            PermissionError: If confirmed is False (human approval gate).
        """
        if not rules:
            return ""

        # Build the rules section
        lines = [
            "",
            _LEARNED_RULES_SECTION_HEADER,
            "",
            "<!-- Auto-generated by `veri learn apply --agents-md`. Do not edit manually. -->",
            "",
        ]
        for rule in rules:
            lines.append(f"- {rule.rule_text} (confidence: {rule.confidence_score:.0%})")
        lines.append("")

        new_section = "\n".join(lines)

        if not confirmed:
            raise PermissionError(new_section)

        # Read existing content
        content = agents_md_path.read_text() if agents_md_path.exists() else ""

        # Remove existing learned rules section if present
        if _LEARNED_RULES_SECTION_HEADER in content:
            idx = content.index(_LEARNED_RULES_SECTION_HEADER)
            content = content[:idx].rstrip()

        # Append new section
        updated = content + new_section
        agents_md_path.write_text(updated)

        logger.info(f"Applied {len(rules)} rules to {agents_md_path}")
        return new_section

    def prune(self, max_age_days: int = 90) -> int:
        """Remove stale rules older than max_age_days with low success rate.

        Args:
            max_age_days: Maximum age in days for rules with success_rate < 0.5.

        Returns:
            Count of pruned rules.
        """
        rules = self.load()
        if not rules:
            return 0

        cutoff = datetime.now() - timedelta(days=max_age_days)
        kept: list[LearnedRule] = []
        pruned = 0

        for rule in rules:
            if rule.created_at < cutoff and rule.success_rate < 0.5:
                pruned += 1
            else:
                kept.append(rule)

        if pruned > 0:
            self.save(kept)

        return pruned
